export const authContent = {
  brandName: 'DPP GRADASI',
  logoUrl: 'https://gradasi.org/uploads/img/logo/1737187847.png',
  backgroundUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?q=80&w=2069&auto=format&fit=crop',
  homePath: '/',
  adminPath: '/admin',
  copyright: '© 2026 DPP GRADASI.',
  socialLinks: [
    { label: 'Facebook', icon: 'ph-facebook-logo', url: 'https://www.facebook.com/gradasiofficial.id' },
    { label: 'Instagram', icon: 'ph-instagram-logo', url: 'https://www.instagram.com/dppgradasi' },
    { label: 'YouTube', icon: 'ph-youtube-logo', url: 'https://www.youtube.com/channel/UCwdjB4LkqcF4Kw5-PoyOb5A' },
  ],
  login: {
    title: 'Selamat Datang',
    subtitle: 'Silakan masuk dengan email terdaftar Anda.',
    heroTitleTop: 'Kembangkan',
    heroTitleHighlight: 'Potensi Digital',
    heroTitleBottom: 'Anda',
    heroDescription: 'Bergabung bersama ribuan pemuda Indonesia lainnya dalam membangun ekosistem digital yang kuat, mandiri, dan inovatif untuk kemajuan bangsa.',
    emailLabel: 'Email Akses',
    emailPlaceholder: 'nama@email.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    forgotButton: 'Lupa Password?',
    submitButton: 'Masuk',
    submittingButton: 'Memproses...',
  },
  forgot: {
    title: 'Lupa Password',
    subtitle: 'Masukkan email terdaftar untuk reset password.',
    emailLabel: 'Email Terdaftar',
    emailPlaceholder: 'nama@email.com',
    submitButton: 'Kirim Link Reset',
    submittingButton: 'Mengirim...',
    backButton: 'Kembali ke Halaman Masuk',
    successTitle: 'Permintaan berhasil dikirim',
    successMessage: 'Jika email terdaftar, tautan reset password akan dikirim ke email tersebut.',
  },
  reset: {
    heroTitleTop: 'Keamanan Akun',
    heroTitleHighlight: 'DPP GRADASI',
    heroDescription: 'Pastikan password Anda kuat dan terlindungi untuk menjaga akses pengelolaan portal resmi Generasi Digital Indonesia.',
    checkingTitle: 'Memvalidasi Tautan...',
    checkingMessage: 'Mohon tunggu sebentar, sistem sedang mengecek masa berlaku tautan Anda.',
    expiredTitle: 'Batas Waktu Tautan Habis',
    expiredMessage: 'Tautan reset/aktivasi ini sudah melewati batas waktu atau telah kedaluwarsa. Silakan lakukan permintaan reset password baru.',
    expiredTip: 'Klik tombol di bawah untuk meminta link reset password baru melalui email Anda.',
    requestNewLink: 'Minta Link Reset Baru',
    backToLogin: 'Kembali ke Halaman Masuk',
    formTitle: 'Atur Password Baru',
    formSubtitle: 'Buat password baru yang kuat untuk akun',
    passwordLabel: 'Password Baru',
    passwordPlaceholder: 'Minimal 6 karakter',
    confirmPasswordLabel: 'Konfirmasi Password Baru',
    confirmPasswordPlaceholder: 'Ulangi password baru',
    submitButton: 'Simpan Password Baru',
    submittingButton: 'Menyimpan...',
    successTitle: 'Password Berhasil Disimpan!',
    successMessage: 'Password Anda telah diperbarui. Silakan masuk menggunakan password baru Anda.',
    loginButton: 'Masuk ke Akun Saya',
  },
}
