export const beritaContent = {
  publicList: {
    badge: 'Pusat Informasi',
    title: 'Semua Informasi & Berita',
    subtitle: 'Temukan seluruh berita terbaru, publikasi, press release, dan pembaruan informasi terkini seputar pergerakan GRADASI.',
    empty: 'Belum ada berita untuk ditampilkan.',
    readMore: 'Baca Berita',
    share: 'Bagikan',
  },
  detail: {
    breadcrumbHome: 'Beranda',
    breadcrumbInfo: 'Informasi',
    defaultTitle: 'Detail Berita',
    shareTitle: 'Bagikan Berita',
    authorBadge: 'Salam Kolaborasi',
    authorName: 'DPP Gradasi',
    authorDescription: 'Tim Redaksi & Publikasi DPP Gradasi',
    notFound: 'Berita tidak ditemukan.',
  },
  admin: {
    title: 'Manajemen Berita',
    searchPlaceholder: 'Cari berita...',
    allStatus: 'Semua Status',
    published: 'Published',
    draft: 'Draft',
    newest: 'Terbaru',
    oldest: 'Terlama',
    reset: 'Reset',
    activeTab: 'Aktif & Draft',
    trashTab: 'Sampah',
    add: 'Tambah',
    edit: 'Edit',
    save: 'Simpan Data',
    cancel: 'Batal',
    empty: 'Tidak ada data untuk ditampilkan.',
  },
  categories: [
    'Berita Nasional',
    'Berita Daerah',
    'Berita Organisasi',
    'Berita Pendidikan',
    'Berita Kebijakan',
    'Teknologi',
    'Edukasi',
    'Event',
    'Tips & Trik',
  ],
}
